name: tradingview_crypto_volume

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Run tradingview_crypto_volume
        run: python tradingview_crypto_volume.py
